---
http_interactions:
- request:
    method: post
    uri: https://api.cloudinary.com/v1_1/<CLOUDINARY_CLOUD_NAME>/image/tags
    body:
      encoding: UTF-8
      string: timestamp=1506982869&tag=attachinary_tmp&public_ids[]=id6&command=remove&signature=a1184f17147d67ae680e20835a8a63f6517a8312&api_key=<CLOUDINARY_API_KEY>
    headers:
      Accept:
      - "*/*; q=0.5, application/xml"
      Accept-Encoding:
      - gzip, deflate
      User-Agent:
      - cld-ruby-1.1.0
      Content-Length:
      - '147'
      Content-Type:
      - application/x-www-form-urlencoded
  response:
    status:
      code: 200
      message: OK
    headers:
      Cache-Control:
      - max-age=0, private, must-revalidate
      Content-Encoding:
      - gzip
      Content-Type:
      - application/json; charset=utf-8
      Date:
      - Mon, 02 Oct 2017 22:21:10 GMT
      Etag:
      - W/"7bd9202622f9de0e2f09217fcdc4d855"
      Server:
      - cloudinary
      Status:
      - 200 OK
      X-Request-Id:
      - 8951c2b4856d195f
      X-Ua-Compatible:
      - IE=Edge,chrome=1
      X-Xss-Protection:
      - 1; mode=block
      Content-Length:
      - '43'
      Connection:
      - keep-alive
    body:
      encoding: ASCII-8BIT
      string: !binary |-
        H4sIAAAAAAAAA6pWKihNyslMjs9MKVayio6tBQAAAP//AwDagr9HEQAAAA==
    http_version: 
  recorded_at: Mon, 02 Oct 2017 22:21:10 GMT
recorded_with: VCR 3.0.3
